"""Initial baseline

Revision ID: 57df7a9f2a4b
Revises: 
Create Date: 2026-01-17 20:09:45.742949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57df7a9f2a4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.drop_index(op.f('idx_analytics_events_chat_id'), table_name='telegram_analytics_events')
    op.drop_index(op.f('idx_analytics_events_chat_ts'), table_name='telegram_analytics_events')
    op.drop_index(op.f('idx_analytics_events_type_ts'), table_name='telegram_analytics_events')
    op.drop_table('telegram_analytics_events')
    op.drop_index(op.f('idx_story_reactions_lookup'), table_name='telegram_story_reactions')
    op.drop_table('telegram_story_reactions')
    op.drop_index(op.f('idx_stories_chat_date'), table_name='telegram_stories')
    op.drop_index(op.f('idx_stories_expire'), table_name='telegram_stories', postgresql_where='(is_archived = false)')
    op.drop_table('telegram_stories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_stories',
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('story_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('views_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('reactions_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('media_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("expire_date <= (date + '7 days'::interval)", name=op.f('check_expire_limit')),
    sa.CheckConstraint('expire_date > date', name=op.f('check_expire_date')),
    sa.PrimaryKeyConstraint('chat_id', 'story_id', name=op.f('telegram_stories_pkey')),
    comment='History of published Telegram stories.'
    )
    op.create_index(op.f('idx_stories_expire'), 'telegram_stories', ['expire_date'], unique=False, postgresql_where='(is_archived = false)')
    op.create_index(op.f('idx_stories_chat_date'), 'telegram_stories', ['chat_id', 'date'], unique=False)
    op.create_table('telegram_story_reactions',
    sa.Column('reaction_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('story_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('reaction', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reacted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('length(reaction) <= 20', name=op.f('check_reaction_len')),
    sa.ForeignKeyConstraint(['chat_id', 'story_id'], ['telegram_stories.chat_id', 'telegram_stories.story_id'], name=op.f('fk_story'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reaction_id', name=op.f('telegram_story_reactions_pkey')),
    sa.UniqueConstraint('chat_id', 'story_id', 'user_id', name=op.f('uq_story_user_reaction'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Current user reactions to stories.'
    )
    op.create_index(op.f('idx_story_reactions_lookup'), 'telegram_story_reactions', ['chat_id', 'story_id'], unique=False)
    op.create_table('telegram_analytics_events',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('source_message_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('event_id', name=op.f('telegram_analytics_events_pkey')),
    comment='Stores granular analytical events from Telegram collector (SLA, offers, etc).'
    )
    op.create_index(op.f('idx_analytics_events_type_ts'), 'telegram_analytics_events', ['event_type', 'timestamp'], unique=False)
    op.create_index(op.f('idx_analytics_events_chat_ts'), 'telegram_analytics_events', ['chat_id', 'timestamp'], unique=False)
    op.create_index(op.f('idx_analytics_events_chat_id'), 'telegram_analytics_events', ['chat_id'], unique=False)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    # ### end Alembic commands ###
